#pragma config(Sensor, S1,     HTIRS2,         sensorI2CCustomFastSkipStates)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-irseeker-v2.h"
const int NUM_READINGS = 1000;
short highResReadings[5][NUM_READINGS];
task main()
{
	const int numAddedBits = 2; // makes 10 bit resolution at 1024 steps
	const int numSamplesAvg = 16;// 4^numAddedBits
	int count = 0;
	int dir_sum = 0;
	int dir_avg=0;
	long sensorSums[5]={0,0,0,0,0};
	float sensorAvg[5];

	while(count<NUM_READINGS)
	{
		int dir = HTIRS2readACDir(HTIRS2);
		int sensors[5][numSamplesAvg];
		for (int k=0;k<numSamplesAvg;k++)
		{
			HTIRS2readAllACStrength(HTIRS2, sensors[0][k], sensors[1][k], sensors[2][k], sensors[3][k], sensors[4][k] );
		}
		long highResSensor[5];
		for(int k=0;k<5;k++)
		{
			long sum = 0;
			for(int i=0;i<numSamplesAvg;i++)
			{
				sum += sensors[k][i];
			}
			highResSensor[k] = sum >> numAddedBits;
		}
		count++;
		dir_sum += dir;
		dir_avg = round(dir_sum/(float)count);
		for (int i=0;i<5;i++)
		{
			highResReadings[i][count-1] = highResSensor[i];
			sensorSums[i] = sensorSums[i]+highResSensor[i];
			sensorAvg[i] = sensorSums[i]/(float)count;
		}
	  /*displayTextLine(1,"Sum: %d",sensorSums[2]);
		displayTextLine(3,"Sensor 1: %f",highResSensor[0]);
		displayTextLine(4,"Sensor 2: %f",highResSensor[1]);
		displayTextLine(5,"Sensor 3: %f",highResSensor[2]);
		displayTextLine(6,"Sensor 4: %f",highResSensor[3]);
		displayTextLine(7,"Sensor 5: %f",highResSensor[4]);*/
	}
	float stdDev[5];
	for(int i =0;i<5;i++)
	{
		float population_mean = sensorAvg[i];
		long sumDeviationSquared = 0;
		for(int c=0;c<NUM_READINGS;c++)
		{
			sumDeviationSquared += pow(abs(highResReadings[i][c] - population_mean),2);
		}
		float variance = sumDeviationSquared/(float)NUM_READINGS;
		stdDev[i] = sqrt(variance);
	}
	displayTextLine(1,"count: %d",count);
	displayTextLine(2,"DIR: %d",dir_avg);
	displayTextLine(3,"S1: %.2f, %.2f",sensorAvg[0],stdDev[0]);
	displayTextLine(4,"S2: %.2f, %.2f",sensorAvg[1],stdDev[1]);
	displayTextLine(5,"S3: %.2f, %.2f",sensorAvg[2],stdDev[2]);
	displayTextLine(6,"S4: %.2f, %.2f",sensorAvg[3],stdDev[3]);
	displayTextLine(7,"S5: %.2f, %.2f",sensorAvg[4],stdDev[4]);
	while(true){}
}
